# -*- coding: utf-8 -*-
"""Hilos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CxsfqibFySUSAQASvJZGOCm7uZvsFXl4
"""

import threading
import random
import numpy as np

def crearMatriz(mat):
    print(f'{threading.current_thread().name} te saluda')
    mat[0,:]=np.arange(1,10)
    mat[1,:]=np.arange(1,18,2)
    mat[2,:]=np.arange(2,19,2)
    print(f'{threading.current_thread().name} se despide')


def ejecutar(matriz,fila,suma):
    print(f'{threading.current_thread().name} te saluda')
    for i in range (9):
        suma[fila]+=matriz[fila,i]

    print(f'{threading.current_thread().name} se despide')


mat=np.zeros((3,9))
suma=[0]*3
hilos=[None]*4

#Creacion hilo 1
hilos[0] = threading.Thread(target=crearMatriz, name='Hilo 1',args=(mat,))
hilos[0].start()
hilos[0].join()

#Creacion hilos 2 al 4
for i in range (1,4):
  hilos[i] = threading.Thread(target=ejecutar, name=f'Hilo {i+1}',args=(mat,i-2,suma))
  hilos[i].start()
  hilos[i].join()

print("Matriz de numeros: \n", mat)
print("Suma de las filas:",suma)